// ひらがなからローマ字への変換マップ
export const hiraganaToRomaji: Record<string, string[]> = {
	あ: ["a"],
	い: ["i"],
	う: ["u"],
	え: ["e"],
	お: ["o"],
	か: ["ka"],
	き: ["ki"],
	く: ["ku"],
	け: ["ke"],
	こ: ["ko"],
	が: ["ga"],
	ぎ: ["gi"],
	ぐ: ["gu"],
	げ: ["ge"],
	ご: ["go"],
	さ: ["sa"],
	し: ["si", "shi"],
	す: ["su"],
	せ: ["se"],
	そ: ["so"],
	ざ: ["za"],
	じ: ["zi", "ji"],
	ず: ["zu"],
	ぜ: ["ze"],
	ぞ: ["zo"],
	た: ["ta"],
	ち: ["ti", "chi"],
	つ: ["tu", "tsu"],
	て: ["te"],
	と: ["to"],
	だ: ["da"],
	ぢ: ["di"],
	づ: ["du"],
	で: ["de"],
	ど: ["do"],
	な: ["na"],
	に: ["ni"],
	ぬ: ["nu"],
	ね: ["ne"],
	の: ["no"],
	は: ["ha"],
	ひ: ["hi"],
	ふ: ["hu", "fu"],
	へ: ["he"],
	ほ: ["ho"],
	ば: ["ba"],
	び: ["bi"],
	ぶ: ["bu"],
	べ: ["be"],
	ぼ: ["bo"],
	ぱ: ["pa"],
	ぴ: ["pi"],
	ぷ: ["pu"],
	ぺ: ["pe"],
	ぽ: ["po"],
	ま: ["ma"],
	み: ["mi"],
	む: ["mu"],
	め: ["me"],
	も: ["mo"],
	や: ["ya"],
	ゆ: ["yu"],
	よ: ["yo"],
	ら: ["ra"],
	り: ["ri"],
	る: ["ru"],
	れ: ["re"],
	ろ: ["ro"],
	わ: ["wa"],
	ゐ: ["wi"],
	ゑ: ["we"],
	を: ["wo"],
	ん: ["n", "nn"],
	ー: ["-"],
	"。": ["."],
	"、": [","],
	"！": ["!"],
	"？": ["?"],
	" ": [" "],
	"　": [" "], // 全角スペースも半角スペースに
	// 小文字
	ぁ: ["xa", "la"],
	ぃ: ["xi", "li"],
	ぅ: ["xu", "lu"],
	ぇ: ["xe", "le"],
	ぉ: ["xo", "lo"],
	っ: ["xtu", "ltu", "xtsu", "ltsu"],
	ゃ: ["xya", "lya"],
	ゅ: ["xyu", "lyu"],
	ょ: ["xyo", "lyo"],
	// 拗音
	きゃ: ["kya"],
	きゅ: ["kyu"],
	きょ: ["kyo"],
	しゃ: ["sya", "sha"],
	しゅ: ["syu", "shu"],
	しょ: ["syo", "sho"],
	ちゃ: ["tya", "cha"],
	ちゅ: ["tyu", "chu"],
	ちょ: ["tyo", "cho"],
	にゃ: ["nya"],
	にゅ: ["nyu"],
	にょ: ["nyo"],
	ひゃ: ["hya"],
	ひゅ: ["hyu"],
	ひょ: ["hyo"],
	みゃ: ["mya"],
	みゅ: ["myu"],
	みょ: ["myo"],
	りゃ: ["rya"],
	りゅ: ["ryu"],
	りょ: ["ryo"],
	ぎゃ: ["gya"],
	ぎゅ: ["gyu"],
	ぎょ: ["gyo"],
	じゃ: ["zya", "ja"],
	じゅ: ["zyu", "ju"],
	じょ: ["zyo", "jo"],
	びゃ: ["bya"],
	びゅ: ["byu"],
	びょ: ["byo"],
	ぴゃ: ["pya"],
	ぴゅ: ["pyu"],
	ぴょ: ["pyo"],
};

// カタカナからローマ字への変換マップ
export const katakanaToRomaji: Record<string, string[]> = {
	ア: ["a"],
	イ: ["i"],
	ウ: ["u"],
	エ: ["e"],
	オ: ["o"],
	カ: ["ka"],
	キ: ["ki"],
	ク: ["ku"],
	ケ: ["ke"],
	コ: ["ko"],
	ガ: ["ga"],
	ギ: ["gi"],
	グ: ["gu"],
	ゲ: ["ge"],
	ゴ: ["go"],
	サ: ["sa"],
	シ: ["si", "shi"],
	ス: ["su"],
	セ: ["se"],
	ソ: ["so"],
	ザ: ["za"],
	ジ: ["zi", "ji"],
	ズ: ["zu"],
	ゼ: ["ze"],
	ゾ: ["zo"],
	タ: ["ta"],
	チ: ["ti", "chi"],
	ツ: ["tu", "tsu"],
	テ: ["te"],
	ト: ["to"],
	ダ: ["da"],
	ヂ: ["di"],
	ヅ: ["du"],
	デ: ["de"],
	ド: ["do"],
	ナ: ["na"],
	ニ: ["ni"],
	ヌ: ["nu"],
	ネ: ["ne"],
	ノ: ["no"],
	ハ: ["ha"],
	ヒ: ["hi"],
	フ: ["hu", "fu"],
	ヘ: ["he"],
	ホ: ["ho"],
	バ: ["ba"],
	ビ: ["bi"],
	ブ: ["bu"],
	ベ: ["be"],
	ボ: ["bo"],
	パ: ["pa"],
	ピ: ["pi"],
	プ: ["pu"],
	ペ: ["pe"],
	ポ: ["po"],
	マ: ["ma"],
	ミ: ["mi"],
	ム: ["mu"],
	メ: ["me"],
	モ: ["mo"],
	ヤ: ["ya"],
	ユ: ["yu"],
	ヨ: ["yo"],
	ラ: ["ra"],
	リ: ["ri"],
	ル: ["ru"],
	レ: ["re"],
	ロ: ["ro"],
	ワ: ["wa"],
	ヰ: ["wi"],
	ヱ: ["we"],
	ヲ: ["wo"],
	ン: ["n", "nn"],
	ー: ["-"],
	"。": ["."],
	"、": [","],
	"！": ["!"],
	"？": ["?"],
	" ": [" "],
	"　": [" "],
	// 小文字
	ァ: ["xa", "la"],
	ィ: ["xi", "li"],
	ゥ: ["xu", "lu"],
	ェ: ["xe", "le"],
	ォ: ["xo", "lo"],
	ッ: ["xtu", "ltu", "xtsu", "ltsu"],
	ャ: ["xya", "lya"],
	ュ: ["xyu", "lyu"],
	ョ: ["xyo", "lyo"],
	// 拗音
	キャ: ["kya"],
	キュ: ["kyu"],
	キョ: ["kyo"],
	シャ: ["sya", "sha"],
	シュ: ["syu", "shu"],
	ショ: ["syo", "sho"],
	チャ: ["tya", "cha"],
	チュ: ["tyu", "chu"],
	チョ: ["tyo", "cho"],
	ニャ: ["nya"],
	ニュ: ["nyu"],
	ニョ: ["nyo"],
	ヒャ: ["hya"],
	ヒュ: ["hyu"],
	ヒョ: ["hyo"],
	ミャ: ["mya"],
	ミュ: ["myu"],
	ミョ: ["myo"],
	リャ: ["rya"],
	リュ: ["ryu"],
	リョ: ["ryo"],
	ギャ: ["gya"],
	ギュ: ["gyu"],
	ギョ: ["gyo"],
	ジャ: ["zya", "ja"],
	ジュ: ["zyu", "ju"],
	ジョ: ["zyo", "jo"],
	ビャ: ["bya"],
	ビュ: ["byu"],
	ビョ: ["byo"],
	ピャ: ["pya"],
	ピュ: ["pyu"],
	ピョ: ["pyo"],
};

// カタカナからひらがなへの変換
export const katakanaToHiragana = (str: string): string => {
	return str.replace(/[\u30A1-\u30F6]/g, (match) => {
		const char = match.charCodeAt(0) - 0x60;
		return String.fromCharCode(char);
	});
};

// 文字がひらがなかどうかチェック
export const isHiragana = (char: string): boolean => {
	return /[\u3041-\u3096]/.test(char);
};

// 文字がカタカナかどうかチェック
export const isKatakana = (char: string): boolean => {
	return /[\u30A1-\u30F6]/.test(char);
};

// ひらがな・カタカナからローマ字を取得
export const getExpectedRomaji = (char: string): string[] => {
	if (isKatakana(char)) {
		return katakanaToRomaji[char] || [];
	}

	if (isHiragana(char)) {
		return hiraganaToRomaji[char] || [];
	}

	// ひらがな・カタカナ以外はそのまま返す
	return [char];
};

// 文字列全体のローマ字表記を取得（表示用）
export const getDisplayRomaji = (char: string): string => {
	const romajiOptions = getExpectedRomaji(char);
	return romajiOptions[0] || char;
};
