name: Biome Lint CI

on:
  pull_request:

jobs:
  quality: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "1.9.4"
      - name: Run Biome
        run: biome ci ./src --config-path=./biome.json
